version: "3.7"
services:
  torq:
    image: "lncapital/torq:latest"
    restart: always
    depends_on:
      - "db"
    command:
      - --config
      - "/home/torq/torq.conf"
      - start
    network_mode: "host"
    volumes:
      - <Path>:/home/torq/torq.conf
  db:
    restart: always
    image: "timescale/timescaledb:latest-pg14"
    environment:
      POSTGRES_PASSWORD: "runningtorq" # Must match db password set above
    volumes:
      - torq_db:/var/lib/postgresql/data
    network_mode: "host"
volumes:
  torq_db:
