apiVersion: v1
kind: ConfigMap
metadata:
  name: lnd-postgres-config
  labels:
    app: lnd-postgres
data:
  POSTGRES_DB: "lndpostgresdb"
  POSTGRES_USER: "<lnd-postgres-user>"
  POSTGRES_PASSWORD: "<lnd-postgres-pass>"
  PGDATA: "/var/lib/postgresql/data/pgdata"
