kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: torq-timescaledb-pv-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
