apiVersion: v1
kind: ConfigMap
metadata:
  name: torq-timescaledb-config
  labels:
    app: torq-timescaledb
data:
  POSTGRES_DB: "torqtimescaledb"
  POSTGRES_USER: "<torq-user>"
  POSTGRES_PASSWORD: "<torq-pass>"
  PGDATA: "/var/lib/postgresql/data/pgdata"
